### ISSUE TITLE
Error when trying the get all the lights

### ISSUE THREAD

**Issue by encompass** [allanbunch/beautifulhue#3]
I was trying to get the examples to work and I got the following error:
>>> from beautifulhue.api import Bridge
>>> bridge = Bridge(device={'ip':'192.168.100.20'}, user={'name':'newdeveloper'})
>>> resource = {'which':'all'}
>>> bridge.light.get(resource)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/BeautifulHue-0.1.2-py2.7.egg/beautifulhue/api/_light.py", line 40, in get
    for (k, v) in content.items():
AttributeError: 'list' object has no attribute 'items'
>>>

**Comment by Edinunzio** [comment]
@allanbunch - I have not yet been able to replicate this error.
*Steps taken*
1. Unplugging all the lights 
2. Using a wrong IP

@encompass - Are you still receiving this error? If so, is there any additional information you have about the conditions surrounding this condition? Thanks!

**Comment by encompass** [comment]
I unfortunately can't test it now. Maybe when I get some more devices in a
few months. It can be closed for now.

**Comment by allanbunch** [comment]
Thanks for the participation.
