### ISSUE TITLE
Remove user

### ISSUE THREAD

**Issue by PanderMusubi** [allanbunch/beautifulhue#7]
How can I remove a user?

**Comment by Edinunzio** [comment]
https://github.com/allanbunch/beautifulhue#delete-1

**Delete bridge user "1234567890"**

from beautifulhue.api import Bridge

bridge = Bridge(device={'ip':'192.168.1.14'}, user={'name':'newdeveloper'})
resource = {'user':{"name": "1234567890"}}
bridge.config.delete(resource)

**Comment by allanbunch** [comment]
Thank you.
